### ISSUE TITLE
Unable to find removeNAN_withImprovedGrammer.csv file

### ISSUE THREAD

**Issue by madhu-basavanna** [Mauville/MedCLIP#1]
hi I tried running the main.ipyb in google colab, but since the code is trying to access the google drive to do a pre-training task and i don't have the file named removeNAN_withImprovedGrammer.csv in my drive, i'm not able to run the code. So can you please upload the file to git or can you provide removeNAN_withImprovedGrammer.csv file in any other means. It would be really helpful for me.

**Comment by Mauville** [comment]
`removeNAN_withImprovedGrammer.csv `was a versioned name of the current `dataset.csv`. Plugging in that name should do the trick.

**Comment by madhu-basavanna** [comment]
thank you

**Comment by madhu-basavanna** [comment]
The dataset repository mentioned in dataset.csv doesn't exist. Its says fatal: repository 'https://git-lfs.github.com/spec/v1/' not found

**Comment by xixihawokao** [comment]
the same problem

**Comment by madhu-basavanna** [comment]
Can you please upload Dataset_MedPix_V1.xlsx so that we can download the dataset using iscrape.ipyb

**Comment by Mauville** [comment]
This is an error with Git LFS, not with the code.
