### ISSUE TITLE
The pre-trained models on MedPix dataset

### ISSUE THREAD

**Issue by o0t1ng0o** [Mauville/MedCLIP#2]
Hi @Mauville,
Thank you for sharing this code repository.
May I ask for the pre-trained models that is trained on MedPix dataset?

Thank you in advance.

**Comment by Mauville** [comment]
The model is `weights.pt`.

**Comment by shishirsinha17** [comment]
Weights.pt doesn't work.  Your code is a scam

**Comment by Mauville** [comment]
Hello @shishirsinha17. Why are the models not working? Have you got any steps to reproduce the problem?
