### ISSUE TITLE
Unable to find url to download Medpix images to output folder?

### ISSUE THREAD

**Issue by Cardano-max** [Mauville/MedCLIP#3]
kindly tell me what url did you use and how can i as i cant find

**Comment by Mauville** [comment]
I invite you to read https://github.com/Mauville/MedCLIP/blob/main/data/readme.adoc
The URLs are on the medpix.csv file.

**Comment by Qasim-Latrobe** [comment]
Hi,
Thanks for sharing the code. The URLs given in MedPix.csv are not working. I am getting HTTP Error 404 if I try to download images to a directory using iscrape.ipynb.
May you please help me to fix this issue.
Thanks!

**Comment by Mauville** [comment]
Moved to https://github.com/Mauville/MedCLIP/issues/7
